name: "Deploy Action"
description: "Deploys the SAM template"

inputs:
  environment-name:
    description: "Environment name"
    required: true
  aws-access-key-id:
    description: "AWS_ACCESS_KEY_ID"
    required: true
  aws-secret-access-key:
    description: "AWS_SECRET_ACCESS_KEY"
    required: true
  pipeline-role:
    description: "IAM role to use to manage pipeline"
    required: true
  deploy-role:
    description: "IAM role to use to deploy resources"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-1
        role-to-assume: ${{ inputs.pipeline-role }}
        role-duration-seconds: 900
        role-session-name: AssumedPipelineRole
        role-skip-session-tagging: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        pip install -U pip
        pip install -r requirements.txt
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: sudo npm install -g aws-cdk@1.127.0
      shell: bash
    - run: cdk diff --context environment=${{ inputs.environment-name }}
      shell: bash
